# Generated by Django 5.2 on 2025-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('verde', 'Verde - Funcionando'), ('amarelo', 'Amarelo - Com defeito parcial'), ('vermelho', 'Vermelho - Fora de uso')], default='verde', max_length=10)),
                ('defeito_relatado', models.TextField(blank=True, null=True)),
                ('data_chamado', models.DateField(auto_now_add=True)),
                ('previsao_conserto', models.DateField(blank=True, null=True)),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
